#!/bin/bash

# Quick Start Guide for Traffic Analyzer

echo "=================================================="
echo "  Traffic Analyzer - Quick Start"
echo "=================================================="
echo ""
echo "This tool captures and analyzes HTTP/HTTPS traffic"
echo "from your browser, similar to Burp Suite."
echo ""
echo "📋 What you need to do:"
echo ""
echo "1. START THE PROXY (in this terminal):"
echo "   ./start.sh"
echo ""
echo "2. OPEN WEB INTERFACE (new terminal):"
echo "   Visit: http://localhost:8081"
echo ""
echo "3. CONFIGURE YOUR BROWSER:"
echo "   Option A - Command Line (recommended for testing):"
echo "   curl -x http://localhost:8080 https://example.com"
echo ""
echo "   Option B - Browser Proxy Settings:"
echo "   - HTTP Proxy: localhost:8080"
echo "   - HTTPS Proxy: localhost:8080"
echo ""
echo "4. TEST THE SETUP (new terminal):"
echo "   python3 test_proxy.py"
echo ""
echo "5. BROWSE THE WEB:"
echo "   All traffic will be captured and displayed"
echo "   in the web interface at localhost:8081"
echo ""
echo "=================================================="
echo ""
read -p "Press Enter to start the proxy server..."

./start.sh
